### ISSUE TITLE
filter argument is ignored in contract pastEvents()

### ISSUE THREAD

**Issue by vporton** [aragon/aragonOS#567] opened 2020-01-25 11:59 UTC
The following code returns more events than it should (`fitler` parameter does not work):
```solidity
    // Should find zero events because this address is with zero probability meet in events
    contract.pastEvents({fromBlock: 0, filter: {v: '0xd6BE8aF190c53D7ca528348a85804BD284Af297C'}})
      .subscribe(events => {
        let textNode = document.createTextNode(events.length);
        document.getElementById('area').appendChild(textNode);
      })
```

1. Download https://github.com/vporton/aragon-events-filter-bug2
1. Start the app.
1. Open "Counter" app.
1. Enter the address of the DAO and click "Test"/
1. You see 9 events found but there should be zero.

**Comment by sohkai** [comment] 2020-01-29 17:45
Duplicate of https://github.com/aragon/aragon.js/issues/362.

**Closed by sohkai** 2020-01-29 17:45 UTC
