### ISSUE TITLE
Test runs inconsistent?

### ISSUE THREAD

**Issue by verdverm** [aragon/aragonOS#237] opened 2018-02-23 02:45 UTC
I think I've been seeing issues in the test environment, both locally and on travis. (see builds for #235 #236)

- `npm test` fails and then passes on a second attempt.
- `npm test` passes and `npm run coverage` fails

Is this a known issue? Any thoughts on the causes?

(I see test and coverage use different networks and binaries for the test network)

Maybe the difference between test and coverage is also due to branches? I've noticed that coverage is not picking up the changed files. (See [235 on travis](https://travis-ci.org/aragon/aragonOS/builds/345084370))

**Comment by sohkai** [comment] 2018-02-23 10:46
The coverage failure in #236 seems to be a sol-cover issue; it seems to not be using a `.call()` on that test.

What does `npm test` fail on?

**Comment by verdverm** [comment] 2018-02-25 11:46
I think the KernelUpgrade section? I'll make note to give a more certain response next time I see it.

**Comment by sohkai** [comment] 2018-05-08 20:10
Closing, since this seems to not be reproducible. Please open again if it's consistent :).

**Closed by sohkai** 2018-05-08 20:10 UTC
